name: Forex Monitor Automation

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 19 * * 1-5" # Runs at 1900 (UTC) every workday (Check https://crontab.guru/)

jobs:
  forex-monitor-automation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python packages
        run: pip install matplotlib pylab numpy pandas

      - name: Run Automation
        run: python run_forex.py ${{ secrets.FOREX_KEY }}
