name: Forex Monitor Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 19 * * 1-5" # Runs at 1900 (UTC) every workday (Check https://crontab.guru/)

jobs:
  forex-monitor-automation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python packages
        run: pip install matplotlib numpy pandas requests tensorflow

      - name: Run Automation
        run: |
          cd src
          python main.py ${{ secrets.FOREX_KEY }}

      - name: Update the repo
        run: |
          git config --global user.name 'VivCh14'
          git config --global user.email 'VivCh14@users.noreply.github.com'
          git commit -am "Update graphs via actions"
          git push
